Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = 'aaitounaS'

  config.vm.provider "virtualbox" do |v|
    v.name = "p2-aaitounaS"
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install net-tools -y
    curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode=644
  SHELL

  config.vm.network "private_network", ip: "192.168.56.110"
end
