Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = 'aaitounaS'

  config.vm.provider "virtualbox" do |v|
    v.name = "p2-aaitounaS"
    v.memory = 2024
    v.cpus = 3
  end
  
  config.vm.provision :shell, path: "scripts/bootstrap.sh"
  config.vm.network "private_network", ip: "192.168.56.110"
end
