Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define "aaitounaS" do |control|
    control.vm.hostname = 'aaitounaS'
    control.vm.provider "virtualbox" do |v|
      v.name = "aaitounaS"
    end
    config.vm.provision :shell, path: "scripts/sbootstrap.sh"
    control.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "kmahediSW" do |control|
    control.vm.hostname = 'kmahediSW'
    control.vm.provider "virtualbox" do |v|
      v.name = "kmahdiSW"
    end
    config.vm.provision :shell, path: "scripts/swbootstrap.sh"
    control.vm.network "private_network", ip: "192.168.56.111"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
end
