Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define "aaitounaS" do |control|
    control.vm.hostname = 'aaitounaS'
    control.vm.provider "virtualbox" do |v|
      v.name = "aaitounaS"
    end
    
    control.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt install net-tools -y
      curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode=644
      while [ ! -d /vagrant ]; do
        echo "Waiting for /vagrant to be ready..."
        sleep 2
      done
      while [ ! -f /var/lib/rancher/k3s/server/node-token ]; do
        echo "Waiting for /var/lib/rancher/k3s/server/node-token to be ready..."
        sleep 2
      done
      TOKEN=$(sudo cat /var/lib/rancher/k3s/server/node-token)
      echo $TOKEN > /vagrant/token
    SHELL
    control.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "kmahediSW" do |control|
    control.vm.hostname = 'kmahediSW'
    control.vm.provider "virtualbox" do |v|
      v.name = "kmahdiSW"
    end
    control.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt install net-tools -y
      TOKEN=$(cat /vagrant/token)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$TOKEN sh -
      rm /vagrant/token
    SHELL
    control.vm.network "private_network", ip: "192.168.56.111"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
end
