Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = 'TestMachine'
  config.vm.provider "virtualbox" do |v|
    v.name = "TestMachine"
    v.memory = 4024
    v.cpus = 5
  end
  config.vm.network "private_network", ip: "192.168.56.112"
end
