apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-configmap
data:
  index.html:  |-
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to App2</title>
    </head>
    <body>
        <h1>Welcome to App2</h1>
        <p>Pod ID: <span id="pod-id"></span></p>
        <p>Node ID: <span id="node-id"></span></p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      volumes:
        - name: app1-vol
          configMap:
            name: app1-configmap
      containers:
        - name: app1
          image: nginx:latest
          volumeMounts:
            - name: app1-vol
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 
  type: ClusterIP