Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = 'Testing'
  config.vm.provider "virtualbox" do |v|
    v.name = "Testing"
    v.memory = 2024
    v.cpus = 3
  end
  config.vm.network "private_network", ip: "192.168.56.110"
end
